### ISSUE TITLE
Errors with import of FDS (.fds) files

### ISSUE THREAD

**Issue by rmcdermo** [firetools/blenderfds28x#16]
Hi Ema,

Few issues here to work on at your pace:

1. Import of "NIST FDS (.fds)", please change to "FDS (.fds)" as we try not to splash NIST around.

2. (More importantly) When I try to import a case to BlenderFDS 2.82a that I have just exported to an FDS file, it fails.  Here are the .fds and .blend files for you to diagnose.
[cogoleto_fire_2019_01.blend.txt](https://github.com/firetools/blenderfds28x/files/4583156/cogoleto_fire_2019_01.blend.txt)
[cogoleto_fire_2019_01.fds.txt](https://github.com/firetools/blenderfds28x/files/4583160/cogoleto_fire_2019_01.fds.txt)

3. Once (2) is working, then it would be nice to also be able to import FDS cases that use viable BINARY geom files (.bingeom).  Let me know when you are ready and I can make a suitable test case.

**Comment by emanuelegissi** [comment]
1. Ok. FDS is known as "NIST FDS" here because "FDS" can have other meanings.
Anyway I do not see a big issue, you are the chief there. Corrected.

2. This is a missing feature, compared to the previous released version. GEOMs are not yet imported. I leave the issue open as a reminder.

3. Yes. The tool is ready in io/bingeom.py
I just need to wire it to importing routines. I will let you know.

**Comment by rmcdermo** [comment]
1. OK, if "NIST FDS" is clearer for you, that is not a big deal.  Ciao

**Comment by emanuelegissi** [comment]
1. Ok, rolling back to NIST FDS then.
2. GEOM import committed. I am not closing the issue because I want to set up verification first.
3. Ongoing

**Comment by emanuelegissi** [comment]
done
